# Generated by Django 3.0 on 2020-11-20 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MusicRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'MusicRoom',
            },
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='data',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='date',
            field=models.DateField(default='2020-10-28'),
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=16)),
                ('user', models.CharField(max_length=32)),
                ('slot_number', models.IntegerField(default=1)),
                ('room', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseapp.MusicRoom', verbose_name='room')),
            ],
        ),
        migrations.AddField(
            model_name='musicroom',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseapp.BookingModel', verbose_name='day'),
        ),
    ]
