# Generated by Django 3.0 on 2020-11-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_auto_20201120_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='username',
            field=models.CharField(default='', max_length=32),
        ),
    ]
